#Worker
apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    app: worker
    tier: worker
    del: appli
spec:
  selector:
    app: worker
    tier: worker
  ports:
    - port: 5672
      targetPort: 5672
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: worker
  labels:
    app: worker
    tier: worker
    del: appli
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
        tier: worker
    spec:
      containers:
      - name: worker
        image: nherbaut/worker:jdev
        env:
        - name: amqp
          value: dns
